name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Install Node.js and build app
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install
          npm run build

      - name: Deploy to EC2
        run: |
          rsync -avz --delete ./build/ ${{ secrets.USER }}@${{ secrets.EC2_IP }}:/var/www/html/

      - name: Restart NGINX
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.EC2_IP }} "sudo systemctl reload nginx"
